# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

lecture:
    path: /lecture/{musiqueId}/{discoursId}
    defaults: { _controller: 'App\Controller\DefaultController::lecture' }

apropos:
    path:  /apropos
    defaults: { _controller: 'App\Controller\DefaultController::apropos' }
    requirements:
        _method:  GET
